services:
  db:
    image: postgres:16-alpine
    container_name: reparasuite-db
    environment:
      POSTGRES_DB: reparasuite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - reparasuite_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reparasuite"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: ./reparasuite-api
      dockerfile: Dockerfile
    container_name: reparasuite-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reparasuite
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123456"
    ports:
      - "8080:8080"

  backoffice:
    build:
      context: ./reparasuite-backoffice
      dockerfile: Dockerfile
    container_name: reparasuite-backoffice
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  reparasuite_db_data:
